# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33236ac73494ff8009874ac3f882aac7b3d1f005d5f07f5cf4a3a42c7a889099f1e738bde60aa5634851d4795e46e92927a7e602e4e12bf07392e7cee578f9d2

test:
  secret_key_base: 41a1286df2e0fead5ebc883482111956990ab21babd12f1f613de905ccd276deb474741dd46ec2f4f4f775f05f5e173c33347ddb9b27f141ed7762cc507e5429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
